# Generated by Django 5.1 on 2025-02-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.AddField(
            model_name='products',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='main.category'),
        ),
    ]
