# Generated by Django 5.1 on 2025-02-03 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_products_category_products_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='tiktok',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='wpp',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='youtube',
        ),
    ]
